theme: jekyll-theme-minimal

title: Making African Connections - Decolonial Futures for Colonial Collections
description: A 2-year AHRC Research Project
logo: /assets/images/AHRC-UoS-SHL-combinedlogo.png
show_downloads: true
